import pandas as pd
import numpy as np
import streamlit as st
from data_generator_final import generate_data  # Updated import
from wordcloud import WordCloud
import matplotlib.pyplot as plt

def analyze_data():
    # Load the dataset generated by data_generator_final
    data = generate_data()  # Assuming generate_data() returns a DataFrame

    # Create filters for user interactivity
    selected_domain = st.selectbox("Select Domain", data['Domain'].unique())
    selected_state = st.selectbox("Select State", data['State'].unique())
    selected_college = st.selectbox("Select College", data['College'].unique())

    # Filter data based on user selection
    filtered_data = data[(data['Domain'] == selected_domain) & 
                         (data['State'] == selected_state) & 
                         (data['College'] == selected_college)]

    # Visualizations
    st.subheader("Participation Trends")
    
    # Domain-wise participation
    domain_participation = data['Domain'].value_counts()
    st.bar_chart(domain_participation)

    # Day-wise participation
    day_participation = data['Date'].value_counts()
    st.line_chart(day_participation)

    # College-wise participation
    college_participation = data['College'].value_counts()
    st.bar_chart(college_participation)

    # State-wise participation
    state_participation = data['State'].value_counts()
    st.bar_chart(state_participation)

    # Feedback distribution
    feedback_distribution = data['Feedback'].value_counts()
    st.bar_chart(feedback_distribution)

    # Generate and display word cloud for domain-wise feedback
    st.subheader("Word Cloud for Domain-wise Feedback")
    feedback_text = ' '.join(data[data['Domain'] == selected_domain]['Feedback'])
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(feedback_text)

    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    st.pyplot(plt)

    return "Analysis completed and visualized."
